### ISSUE TITLE
NullPointerException on back item

### ISSUE THREAD

**Issue by dacasals** [Angads25/android-filepicker#36]
Hello, when the first listview is loaded with directories and files of the specified path, and you press the first element to return (...), the application ends with errors. An uncontrolled nullPointerException is thrown.

**Comment by npes87184** [comment]
You should indicate the correct root directory. For example: "/".

**Comment by themysteq** [comment]
@dacasals as docs said you should set your `root` property as the most parent - where the user can't go higher. It's boundary directory. The `offset` property is the directory which you want to show to user when `dialog.show()` is called.  `offset` must be sub-directory of `root` or you will get `NullPointerException`.

In my example the most parent directory is `Environment.getExternalStorageDirectory()` so :
```java
properties.root = Environment.getExternalStorageDirectory(); 
// in my device it's "/storage/emulated/0"

properties.offset = Environment.getExternalStorageDirectory()+ "/subfolder";
 // will be "/storage/emulated/0/subfolder"
```

**Comment by singhangadin** [comment]
Hi @dacasals ,
Just a few days after releasing library I received an email and an [issue](https://github.com/Angads25/android-filepicker/issues/34) with a similar concern.
Here I will explain what was the issue with the library: 
By default, library sets offset and root to sdcard location, You can see [here](https://github.com/Angads25/android-filepicker/commit/f22da3899ecb703d4e85c715d2fa6c174146f38d#diff-a4a355e997d11e4ea2e16aa7569f3bf0R82).
While initializing the list, dialog checks whether an offset has been set or not. If set and location are valid, offset directory's files are [shown](https://github.com/Angads25/android-filepicker/commit/f22da3899ecb703d4e85c715d2fa6c174146f38d#diff-f314181d6d92833d254d51a235eaf2ceR172) in the dialog. [This](https://github.com/Angads25/android-filepicker/commit/f22da3899ecb703d4e85c715d2fa6c174146f38d#diff-f314181d6d92833d254d51a235eaf2ceR174) condition also adds the parent directory in the same listview. Now since you are presently in the root directory (as root and offset are same), parent directory shouldn't have been shown in the first place, next you cannot go before sdcard directory (You can't access any directory before sdcard as app don't have permission for that). Hence clicking the ... gave a NullpointerException. It was added in the root listview and wasn't supposed to be there. So in v1.0.9, I added extra checks to validate offset (That I should have added before!). You can see them [here](https://github.com/Angads25/android-filepicker/commit/fb8871608e2dbd67c429c16b390813db91ddb605#diff-f314181d6d92833d254d51a235eaf2ceR202). This won't set an offset if offset equals root directory path or isn't a subdirectory of the root (Which covers the case @themysteq has mentioned). Hopefully, this was the case! If not, I would like to know what are the values you have set in root and offset properties. It is possible that os doesn't provide permission to access the directory which is the parent of offset.

P.S.: Lines tagged in links are marked with yellow color.
