### ISSUE TITLE
Remove params from application in AndroidManifest.xml

### ISSUE THREAD

**Issue by alexeyvasilyev** [Angads25/android-filepicker#42]
Please remove
```
android:allowBackup="true"
android:supportsRtl="true"
```

from AndroidManifest.xml file. Every app has their own policy regarding using backup or RTL. No reason for such params in 3d party library.

Also remove
```
uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
```
This parameter also should be controllable by the app itself. Not by 3d party library.

**Comment by singhangadin** [comment]
@alexeyvasilyev 
Unfortunately `uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"` tag cannot be removed from the manifest as library depends upon it. If developer forgets to add it, then app may misbehave. It is done by most libraries. You can check any networking library, It has internet permission.

**Comment by alexeyvasilyev** [comment]
My app for instance already has WRITE_EXTERNAL_STORAGE permission. Then why do I need read permission auto added?

**Comment by singhangadin** [comment]
Having write permission doesn't actually mean you could read a file present in SD Card. Since library won't work without this permission, then adding it would be a compulsion. So whether library adds it or your application, it won't make a difference. Worst case would be if permission is added both in your app manifest and library. For that during compilation of apk, android merges the manifest and there won't be any repetitions of permission. If permission is removed from library's manifest and app developer forgets to add in the application. Then dialog might misbehave. So in my opinion, adding permission to the Library would be the best option. Guess what? Now you don't have to add permission in your manifest, wouldn't that make things easier for you.
